import React from 'react';
import './index.css';


function App() {
return (
<div className="App">
<header className="App-header">
<div className="header-content">

    <h1>Full Stack Developer Portfolio</h1>
    </div>
 
</header>
<main className="main-content">
  <section className="about-section">
      <div className="section-header">
            <h2>About Me</h2>
                </div>
                    <div className="about-content">
                          <img src="https://avatars.githubusercontent.com/u/70350694?v=4" alt="Profile" className="profile-image" />
                                
                                      <p>
                                              Hello! I'm AKINPELU ABIODUN MOSES, a passionate full stack developer with expertise in web development technologies. I have 7 years of experience building scalable and high-performance web applications using modern frameworks and libraries.
                                                    </p>
                                                        </div>
                                                          </section>

                                                            <section className="skills-section">
                                                                <div className="section-header">
                                                                      <h2>Skills</h2>
                                                                          </div>
                                                                              <div className="skills-content">
                                                                                    <ul>
                                                                                            <li>Front-end Development (HTML, CSS, JavaScript, React)</li>
                                                                                                    <li>Back-end Development (Node.js, PHP)</li>
                                                                                                            <li>Database Management (MySQL)</li>
                                                                                                                    <li>API Development and Integration</li>
                                                                                                                            <li>Version Control (Git, GitHub)</li>
                                                                                                                                    <li>Agile Development Methodologies</li>
                                                                                                                                          </ul>
                                                                                                                                              </div>
                                                                                                                                                </section>

                                                                                                                                                  <section className="projects-section">
                                                                                                                                                      <div className="section-header">
                                                                                                                                                            <h2>Recent Projects</h2>
                                                                                                                                                                </div>
                                                                                                                                                                    <div className="projects-content">
                                                                                                                                                                          <div className="project">
                                                                                                                                                                                  <h3>Travel and Tour Website Development</h3>
                                                                                                                                                                                          <p>Designed and developed a responsive website for a travel and tour company. Implemented features such as tour packages listing, booking forms, and user authentication.</p>
                                                                                                                                                                                                  <p>Technologies used: React, Node.js, HTML, CSS, JavaScript, PHP, MySQL</p>
                                                                                                                                                                                                          <a href="https://uniqueachieversbusiness.com.ng/#" target="_blank" rel="noopener noreferrer">Visit Website</a>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                      <div className="project">
                                                                                                                                                                                                                              <h3>Oil and Gas Website Development</h3>
                                                                                                                                                                                                                                      <p>Created a website for OPPENHEIMER Resources, an oil and gas service provider. Showcased their services, products, and procurement offerings.</p>
                                                                                                                                                                                                                                              <p>Technologies used: HTML, CSS, JavaScript</p>
                                                                                                                                                                                                                                                      <a href="https://oppenheimerresources.com/" target="_blank" rel="noopener noreferrer">Visit Website</a>
                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                  <div className="project">
                                                                                                                                                                                                                                                                          <h3>Radio Station Web App</h3>
                                                                                                                                                                                                                                                                                  <p>Developed a web application for Radiobox, a radio station. Implemented features such as live streaming, program schedule, and on-demand playback.</p>
                                                                                                                                                                                                                                                                                          <p>Technologies used: React, Node.js, HTML, CSS, JavaScript, PHP, MySQL</p>
                                                                                                                                                                                                                                                                                                  <a href="https://radiobox.com.ng/" target="_blank" rel="noopener noreferrer">Visit Website</a>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                <section className="education-section">
                                                                                                                                                                                                                                                                                                                    <div className="section-header">
                                                                                                                                                                                                                                                                                                                          <h2>Education</h2>
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                  <div className="education-content">
                                                                                                                                                                                                                                                                                                                                       <h3> University Name</h3>
                                                                                                                                                                                                                                                                                                                                       <h3>OND Mechanical Engineering </h3>
                                                                                                                                                                                                                                                                                                                                       <p>Graduation year : 2021</p>
                                                                                                                                                                                                                                                                                                                                             <h3>Bachelor of Mathematics</h3>
                                                                                                                                                                                                                                                                                                                                                   <p>Graduation Year: 2023</p>
                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                               </section>
                                                                                                                                                                                                                                                                                                                                                               <section className="contact-section">
                                                                                                                                                                                                                                                                                                                                                                 <div className="section-header">
                                                                                                                                                                                                                                                                                                                                                                     <h2>Contact</h2>
                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                         <div className="contact-content">
                                                                                                                                                                                                                                                                                                                                                                             <div className="contact-info">
                                                                                                                                                                                                                                                                                                                                                                                   <h3>Address</h3>
                                                                                                                                                                                                                                                                                                                                                                                         <p>11 folawiyo bankole street,ikete,surulere,lagos</p>
                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                 <div className="contact-info">
                                                                                                                                                                                                                                                                                                                                                                                                       <h3>Email</h3>
                                                                                                                                                                                                                                                                                                                                                                                                             <p>abiodunmosesakinpelu@gmail.com</p>
                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="contact-info">
                                                                                                                                                                                                                                                                                                                                                                                                                           <h3>Phone</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                 <p>+2348168766206</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="contact-info">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>GitHub</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="https://github.com/abiodun6876" target="_blank" rel="noopener noreferrer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Visit GitHub Profile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                       </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                         </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                           <footer className="footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                           <p>&copy; 2023 AKINPELU ABIODUN MOSES. All rights reserved.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                             </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
);
}

export default App;
